name: main CI CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  env:
    SPRING_PROFILES_ACTIVE: main
    LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
    LIGHTSAIL_SSH_HOST: ${{ secrets.LIGHTSAIL_SSH_HOST }}
    LIGHTSAIL_USER: ${{ secrets.LIGHTSAIL_USER }}
    AWS_REGION: ap-northeast-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # jdk 설정
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # gradle cache 설정
      - name: gradle 캐시하기
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 프로덕션 환경 설정
      - name: 프로덕션 환경 설정
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{secrets.PROPERTIES_PROD }}" > ./application.yml

        shell: bash

        ## gradle 빌드
      - name: gradle 빌드
        run: ./gradlew build -x test


        # AWS 인증
      - name: AWS 인증
        uses: aws-actions/configure-aws-credentials@v1
        with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws-region: ${{ env.AWS_REGION }}

      # AWS 인증이 완료되었는지 테스트합니다.
      - name: AWS Lightsail에 연결되었는지 확인
        run: aws configure list

      # 배포 자동화
      - name: 배포 자동화
        run: |
            ssh -i ${{ secrets.LIGHTSAIL_SSH_KEY }} ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_SSH_HOST }} "cd /home/ubuntu/barabara && ./gradlew build -x test && sudo systemctl restart geulkkoli"
            shell: bash